name: VOEMonitor
options:
  bundleIdPrefix: com.github.yefimtsev
  xcodeVersion: "26.2"
  generateEmptyDirectories: true
  developmentLanguage: uk
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Config/Base.xcconfig
  Release: Config/Base.xcconfig
targets:
  VOEMonitor:
    type: application
    platform: macOS
    sources:
      - path: Shared
      - path: macOS
        excludes:
          - "Resources/**"
    configFiles:
      Debug: Config/Debug-macOS.xcconfig
      Release: Config/Release-macOS.xcconfig

  VOEMonitorIOS:
    type: application
    platform: iOS
    sources:
      - path: Shared
      - path: iOS
        excludes:
          - "Resources/**"
    dependencies:
      - target: VOEWidget
        embed: true
        codeSign: true
    configFiles:
      Debug: Config/Debug-iOS.xcconfig
      Release: Config/Release-iOS.xcconfig

  VOEWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: Shared
      - path: Widget
        excludes:
          - "**/*.lproj/**"
    configFiles:
      Debug: Config/Debug-Widget.xcconfig
      Release: Config/Release-Widget.xcconfig
    settings:
      base:
        GENERATE_INFOPLIST_FILE: NO
schemes:
  VOEMonitor:
    build:
      targets:
        VOEMonitor: all
  VOEMonitorIOS:
    build:
      targets:
        VOEMonitorIOS: all
        VOEWidget: all
    run:
      config: Debug
